### ISSUE TITLE
don't work with http proxy with authentification

### ISSUE THREAD

**Issue by letroll** [ueffel/Keypirinha-PackageControl#1]
Hello, first thank you for your work.

I have the following stacktrace with my corp proxy :
Traceback (most recent call last):
  File "Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 56, in on_start
  File "\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 285, in _check_installed
  File "Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 308, in _get_package
13:31:46.563 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained: HTTP Error 407: Proxy Authentication Required
13:31:55.621 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained: HTTP Error 407: Proxy Authentication Required
13:31:55.622 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 172, in on_suggest

**Comment by ueffel** [comment]
Did you configure the proxy within Keypirinha's network settings?
What kind of authentication is used? 
According to [this comment for keypirinha itself](https://github.com/Keypirinha/Keypirinha/issues/243#issuecomment-334117383) NTLM authentication is not supported yet.

**Comment by letroll** [comment]
yes I have, and I think it's NTLM. It's strange because, with my configuration other plugin like google translate works.

**Comment by ueffel** [comment]
I'm doing else code-wise. strange...

**Comment by ueffel** [comment]
@letroll Any news on this?

**Comment by ueffel** [comment]
Closing this due to lack of interest.
