### ISSUE TITLE
Error with PackageControl in parsing date time

### ISSUE THREAD

**Issue by AbhishekTripathi** [ueffel/Keypirinha-PackageControl#11]
Windows 10 version 1909 (18363.1139)
Region: India
Format: English (India)
KeyPirinha version: 2.25

_packagecontrol.ini content_
``` 
[main]
repository = https://ue.spdns.de/packagecontrol/packages.json
```

*Error in Console:*

12:29:21.649 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "D:\Dropbox\Tools\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 410, in _get_available_packages
  File "D:\Dropbox\Tools\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 512, in _get_last_run
  File "D:\Dropbox\Tools\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 499, in _make_date
  File "lib\_strptime.py", line 577, in _strptime_datetime
  File "lib\_strptime.py", line 359, in _strptime
ValueError: time data '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+0000' does not match format '%Y-%m-%dT%H:%M:%S%z'
12:29:21.650 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\Dropbox\Tools\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 200, in on_suggest

**Comment by ueffel** [comment]
Can you post the content of the following file?
`D:\Dropbox\Tools\Keypirinha\portable\Local\Packages\PackageControl\last.run`

This file saves the date of the last time the repository was contacted to update the available packages. It normally should look like this:

```
2020-10-27T17:25:29
```

The file seems to be corrupted somehow.
Your quick fix would be to just delete this file.

Maybe I should add some fault tolerance for this case.

**Comment by ueffel** [comment]
Same as #8, apparently. No idea how that happens, but I'll add some fault tolerance for these kind of broken files.

**Comment by AbhishekTripathi** [comment]
Deleting the corrupted last.run file actually helped. I am attaching the file with corrupted content.

[last.zip](https://github.com/ueffel/Keypirinha-PackageControl/files/5480762/last.zip)
