### ISSUE TITLE
Error when attempting to install keypirinha-emojii

### ISSUE THREAD

**Issue by ChildishGiant** [ueffel/Keypirinha-PackageControl#12]
```
18:21:18.435 ** ERROR: PackageControl.PackageControl: Error occurred while executing command 'PackageControl: Install Package | keypirinha-emojii (by @andriykrefer)'
Traceback (most recent call last):
  File "lib\urllib\request.py", line 1317, in do_open
  File "lib\http\client.py", line 1244, in request
  File "lib\http\client.py", line 1290, in _send_request
  File "lib\http\client.py", line 1239, in endheaders
  File "lib\http\client.py", line 1026, in _send_output
  File "lib\http\client.py", line 966, in send
  File "lib\http\client.py", line 1406, in connect
  File "lib\http\client.py", line 938, in connect
  File "lib\socket.py", line 727, in create_connection
  File "lib\socket.py", line 716, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 245, in on_execute
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 537, in _install_package
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\lib\package.py", line 21, in download
  File "C:\Program Files\Keypirinha\python\site\keypirinha_net.py", line 40, in open
    fullurl, *args, data=data, timeout=timeout, **kwargs)
  File "lib\urllib\request.py", line 531, in open
  File "lib\urllib\request.py", line 641, in http_response
  File "lib\urllib\request.py", line 563, in error
  File "lib\urllib\request.py", line 503, in _call_chain
  File "lib\urllib\request.py", line 755, in http_error_302
  File "lib\urllib\request.py", line 525, in open
  File "lib\urllib\request.py", line 543, in _open
  File "lib\urllib\request.py", line 503, in _call_chain
  File "lib\urllib\request.py", line 1360, in https_open
  File "lib\urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error timed out>
```

When trying to install again it says this:
`18:28:42.404 WARNING: PackageControl.PackageControl: Package 'keypirinha-emojii' already installed`

When I look at the installed packages in packagecontrol.ini it's not listed but must be somewhere?

**Comment by ueffel** [comment]
Seems to me that the download of the package from github.com failed but the `.keypirinha-package` was created (and is probably 0-byte)
It would be located at `C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\Emojii.keypirinha-package` on your system.

You could try to use "PackageControl: Reinstall untracked package from repository" to try the install again.

Also it is not a good idea to place a portable application in `C:\Program Files`. Usually portable apps need write permission in the directory they're placed. You would always need to run the app as administrator to have that.

TODO for me: Make sure the corrupt (incomplete) file gets cleaned up in case of an error.

**Comment by polyvertex** [comment]
@ChildishGiant note that running Keypirinha from `C:\Program Files\` is not a good idea in portable mode as you may stumble upon file creation rights issues. You should either relocate KP (so to keep running in portable mode), or migrate KP to its "Installed mode". More info [here](https://keypirinha.com/install.html#installed-vs-portable-mode).
