### ISSUE TITLE
The plugin shows an error on console and does not work

### ISSUE THREAD

**Issue by piovisqui** [ueffel/Keypirinha-PackageControl#3]
I tried to install it copying directly to the \Keypirinha\portable\Profile\InstalledPackages and using the import command. Manual install of other packages, like WindowsApps.keypirinha-package works.

Thanks in advance.

`>>> import keypirinha as kp,keypirinha_net as kpn,os;p="PackageControl.keypirinha-package";d=kpn.build_urllib_opener().open("https://github.com/ueffel/Keypirinha-PackageControl/releases/download/0.2/"+p);pb=d.read();d.close();f=open(os.path.join(kp.installed_package_dir(),p),"wb");f.write(pb);f.close()
15108
15:08:21.541 Plugin loaded: PackageControl.PackageControl (instance #1)
15:08:22.554 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 376, in _get_available_packages
  File "C:\Users\user\OneDrive\utils\Keypirinha\python\site\keypirinha_net.py", line 40, in open
    fullurl, *args, data=data, timeout=timeout, **kwargs)
  File "lib\urllib\request.py", line 532, in open
  File "lib\urllib\request.py", line 642, in http_response
  File "lib\urllib\request.py", line 570, in error
  File "lib\urllib\request.py", line 504, in _call_chain
  File "lib\urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
15:08:22.555 ** ERROR: Error from PackageControl.PackageControl.on_start: <class 'TypeError'>: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 62, in on_start
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 292, in _check_installed
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 326, in _get_package
15:26:11.020 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 376, in _get_available_packages
  File "C:\Users\user\OneDrive\utils\Keypirinha\python\site\keypirinha_net.py", line 40, in open
    fullurl, *args, data=data, timeout=timeout, **kwargs)
  File "lib\urllib\request.py", line 532, in open
  File "lib\urllib\request.py", line 642, in http_response
  File "lib\urllib\request.py", line 570, in error
  File "lib\urllib\request.py", line 504, in _call_chain
  File "lib\urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
15:26:11.515 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\user\OneDrive\utils\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 376, in _get_available_packages
  File "C:\Users\user\OneDrive\utils\Keypirinha\python\site\keypirinha_net.py", line 40, in open
    fullurl, *args, data=data, timeout=timeout, **kwargs)
  File "lib\urllib\request.py", line 532, in open
  File "lib\urllib\request.py", line 642, in http_response
  File "lib\urllib\request.py", line 570, in error
  File "lib\urllib\request.py", line 504, in _call_chain
  File "lib\urllib\request.py", line 650, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
15:26:11.515 ** ERROR: PackageControl.PackageControl: Error occurred while executing command 'PackageControl: Update Repository List'
Traceback (most recent call last):`

**Comment by ueffel** [comment]
hm they just took down my webspace with the package repository file. you can change your url to my new location:
```ini
[main]
repository = https://ue.spdns.de/packagecontrol/packages.json
```

i will change the default repository url in the next release soon

**Comment by piovisqui** [comment]
Thanks, it works now.
