### ISSUE TITLE
Freezes on collecting packages...

### ISSUE THREAD

**Issue by karakatsanism** [ueffel/Keypirinha-PackageControl#8]
Hi, I am trying to install some package but it gets stuck at collecting packages. I am using keypirinha 2.23
<img width="491" alt="2018-12-23 13_14_01-mozilla firefox" src="https://user-images.githubusercontent.com/20352640/50383097-b1012400-06b5-11e9-8477-b7c8776c6054.png">

**Comment by ueffel** [comment]
Anything in the keypirinha console? Looks like you can't reach the repository.
Maybe some missing proxy settings or something?

**Comment by karakatsanism** [comment]
I get this: 
19:02:57.512 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable

**Comment by karakatsanism** [comment]
`19:02:10.668 ** ERROR: PackageControl.PackageControl: Error occurred while executing command 'PackageControl: Update Repository List'
Traceback (most recent call last):
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 228, in on_execute
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 299, in _check_installed
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 333, in _get_package
TypeError: 'NoneType' object is not iterable
19:02:57.512 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 365, in _get_available_packages
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 442, in _get_last_run
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 429, in _make_date
  File "lib\_strptime.py", line 565, in _strptime_datetime
  File "lib\_strptime.py", line 362, in _strptime
ValueError: time data '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+0000' does not match format '%Y-%m-%dT%H:%M:%S%z'
19:02:57.512 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable`

**Comment by karakatsanism** [comment]
And this
19:02:10.668 ** ERROR: PackageControl.PackageControl: Error occurred while executing command 'PackageControl: Update Repository List'
Traceback (most recent call last):
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 228, in on_execute
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 299, in _check_installed
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 333, in _get_package
TypeError: 'NoneType' object is not iterable
19:02:57.512 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 365, in _get_available_packages
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 442, in _get_last_run
  File "C:\Users\Michalis\Documents\Keypirinha\portable\Profile\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 429, in _make_date
  File "lib\_strptime.py", line 565, in _strptime_datetime
  File "lib\_strptime.py", line 362, in _strptime
ValueError: time data '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+0000' does not match format '%Y-%m-%dT%H:%M:%S%z'
19:02:57.512 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable

**Comment by ueffel** [comment]
There seems to be a problem with the `last.run` file.
Can you try to delete it and run the install package command again?
The file is located in `<Keypirinha_Home>\portable\Local\Packages\PackageControl\` in portable mode or `%LOCALAPPDATA%\Keypirinha\Packages\PackageControl\`

**Comment by karakatsanism** [comment]
didn't work... uninstalled and re-installed packagecontrol and everything works fine. thanks for the help

**Comment by ueffel** [comment]
Alright. Closing this then.
